os: unstable

install:
  - ps: Get-PackageProvider -Name NuGet -ForceBootstrap | Out-Null
  - ps: Set-PSRepository -Name PSGallery -InstallationPolicy Trusted 
  - ps: Install-Module -Name "Pester","PSScriptAnalyzer" -Scope CurrentUser
  - ps: Invoke-ScriptAnalyzer -Path .

build_script:
  - ps: .\bootstrap.ps1


