os: Windows Server 2012

install:
  - ps: (new-object Net.WebClient).DownloadString("http://psget.net/GetPsGet.ps1") | iex
  - ps: Install-Module -Name PSScriptAnalyzer
  - ps: Invoke-ScriptAnalyzer -Path .

build_script:
  - ps: .\bootstrap.ps1


