#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

files=`git diff HEAD --name-only --diff-filter=AM | awk '$1=$1' ORS=' '`
iformat  -r -m *.as,*.mxml,*.css,*.properties $files -s /flex.xml

git add $files

